= automx2: Email client configuration made easy
:keywords: autoconfig, autodiscover, mobileconfig, automx, automx2
:author: Patrick Ben Koetter
:email: p@sys4.de
:subject: automx2: Email client configuration made easy
:revnumber: 1.0.0
:revdate: 11.12.2019
:copyright: (C) sys4 AG
:publisher: sys4 AG
:lang: en
:hyphens: en
:encoding: UTF-8
:pdf-version: 1.7
:toc:
:toclevels: 3
:sectnums:
:pagenums:
:icons: font
// :iconsdir: ../layout/icons
// :icontype: svg
:title-page:
:media: print
:asciidoctor-diagram:

automx2 makes configuring a mail account easy. It unites methods for automated
mailbox configuration from Apple
(https://support.apple.com/de-de/guide/profile-manager/pmdbd71ebc9/mac[mobileconfig]),
Microsoft
(https://docs.microsoft.com/de-de/exchange/architecture/client-access/autodiscover?view=exchserver-2019[autodiscover])
and Mozilla
(https://developer.mozilla.org/de/docs/Mozilla/Thunderbird/Autokonfiguration[autoconfig])
in one tool. automx2 is successor to automx. It has been designed to be easier
to setup, easier to configure and easier use.


This document explains how automx2 works, how <<automatedmailboxconfiguration,
Automated Mailbox Configuration>> works and what it takes to install and
configure automx2. If you are already familiar with automated mailbox
configuration methods you may want skip the following sections and jump right
ahead to <<automx2installation>> and <<automx2setup>>.


== How does automx2 work?

automx2 is a webservice. It sits behind a web server and waits for
configuration requests. When a mail client requests configuration it contacts
the web server. The web server then acts as a proxy and forwards all requests
to the web service aka automx2.

[ditaa,howitworks,svg,align=center]
....
+------------+         +------------+        +------------+
|            |         |            |        |            |
|            |  HTTPS  |            |  1234  |            |
| mailclient |<------->| webserver  |<------>| webservice |
|            |         |  (nginx)   |        |  (automx2) |
|            |         |            |        |            |
+------------+         +------------+        +------------+
....

[[automatedmailboxconfiguration]]
include::MAILBOXCONFIGURATION.asciidoc[]

[[automx2installation]]
include::INSTALLATION.asciidoc[]

[[automx2setup]]
include::CONFIGURATION.asciidoc[]


== About automx2

The project resides as https://gitlab.com/automx/automx2[automx/automx2] on
GitLab. Please use the projects https://gitlab.com/automx/automx2/issues[issue
tracker] if you find bugs. To discuss usage and other topics join us on the
https://mail.sys4.de/cgi-bin/mailman/listinfo/automx-users[automx-users]
mailing list.

automx2 was written by https://gitlab.com/rseichter[Ralph Seichter] for
https://sys4.de[sys4 AG]. It has 100% test coverage and is mirrored to
https://github.com/rseichter/automx2[rseichter/automx2] on GitHub.


