= automx2: Email client configuration made easy
:keywords: autoconfig, autodiscover, mobileconfig, automx, automx2
:author: Patrick Ben Koetter
:email: p@sys4.de
:subject: automx2: Email client configuration made easy
:revnumber: 2019.0
:revdate: 13.12.2019
:copyright: (C) sys4 AG
:publisher: sys4 AG
:lang: en
:hyphens: en
:encoding: UTF-8
:pdf-version: 1.7
:icons: font
:title-page:
:media: print
:asciidoctor-diagram:

automx2 makes configuring a mail account easy. It unites methods for automated
mailbox configuration from Apple
(https://support.apple.com/de-de/guide/profile-manager/pmdbd71ebc9/mac[mobileconfig]),
Microsoft
(https://docs.microsoft.com/de-de/exchange/architecture/client-access/autodiscover?view=exchserver-2019[autodiscover])
and Mozilla
(https://developer.mozilla.org/de/docs/Mozilla/Thunderbird/Autokonfiguration[autoconfig])
in one tool. automx2 is successor to automx. It has been designed to be easier
to setup, easier to configure and easier to use.


== Documentation

automx2 comes with documentation that explains how automated mail account
configuration works, how automx2 works and how you install and configure
automx2.

All link:doc/automx2.adoc[documentation] is stored in the `doc` subdirectory. You
can read it file by file using a text reader or all files as one if you point
your browser to +automx2.html+.


== About automx2

The project is hosted on https://gitlab.com/automx/automx2[GitLab].
Please use the project's https://gitlab.com/automx/automx2/issues[issue tracker] if you find bugs.
If you have questions or want to discuss usage and other topics, join us on the
https://mail.sys4.de/cgi-bin/mailman/listinfo/automx-users[automx-users] mailing list.

automx2 was written by https://gitlab.com/rseichter[Ralph Seichter] for https://sys4.de[sys4 AG].
