== Configuring automx2

automx2 uses a file to read runtime instructions from and a database to lookup
mail account configuration data.


=== Runtime configuration

The configuration file defines automx2 runtime behaviour and it specifies the
backend automx2 should read mailbox account configuration data from.

[NOTE]
.Running without runtime config
====
If you launch automx2 without a configuration file, it will use internal
defaults. These are suitable for testing only. Launched without a config it
will use an in-memory SQLite database and all data will be lost once the
application terminates.
====

During startup automx2 looks for runtime configuration instructions in
the following locations:

[[configurationlocations]]
[source,txt]
----
AUTOMX2_CONF     <1>
~/.automx2.conf  <2>
/etc/automx2/automx2.conf
/etc/automx2.conf
----

<1> If this environment variable exists, it will be used. The value must point
    to a location where automx2 can read configuration from. If the specified
    file does not exist, the search will continue.
<2> If automx2 finds `.automx2.conf` in the `$HOME` of the user that runs
    automx2, it will be used.

To specify parameters and options automx2 uses an
link:https://docs.python.org/3.7/library/configparser.html#supported-ini-file-structure[INI]-style
configuration syntax. The
link:https://gitlab.com/automx/automx2/raw/master/contrib/automx2-sample.conf[example
configuration] that ships with automx2 looks like this:

[source,ini]
----
include::../contrib/automx2-sample.conf[]
----

Place the content of the example configuration into one of the configuration
locations automx2 looks for and adapt it to your needs. Then configure the
database backend with data that suits your setup.


=== Testing standalone automx2

If you want to verify a vanilla install of automx2 works you can populate it
with the (internal) test data. Start it as described in section
<<runningautomx2>> and send the following request to populate your database
with the internal test data:

[source,terminal]
----
curl http://127.0.0.1:4243/initdb/
----

This example assumes you are running automx2 on localhost listening on TCP
port 4243, which is the suggested default port.

Once you have populated the database with sample data you can test if automx2
works. Use curl to send an account configuration request for +user@example.com+:

[source,terminal]
----
curl 'http://127.0.0.1:4243/mail/config-v1.1.xml?emailaddress=user@example.com'
----

As shown in the example, make sure to use quotes as necessary to prevent your shell
from matching/replacing patterns.

=== Database configuration

automx2 uses the SQLAlchemy toolkit to access databases. This allows a variety
of databases, aka link:https://docs.sqlalchemy.org/en/13/dialects/[dialects],
to be used, simply by defining the appropriate connection URL.

[NOTE]
.Browser/API based configuration
====
At the moment you will have to add database entries manually. We want to add
the capability to do that via a webservice in an upcoming version, but we
haven't planned when we would add this yet. Please feel free to contact
us if you want to sponsor this feature. Sponsoring will certainly help to
make this feature become a priority.
====

[NOTE]
.Database support
====
While you probably already have SQLite support available on your local machine,
you may need to install additional Python packages for PostgreSQL, MySQL, etc.
Detailed instructions to support a particular database dialect are out of scope
for this document. Please search the Internet for detailed instructions on supporting
a particular dialect. The SQLAlchemy documentation provides a useful starting point.
====

==== SQLite

This section demonstrates what you need to do to in order to use SQLite version
3 or higher as a backend database for automx2.

[source,bash]
----
$ sqlite3 --version
3.34.1 2021-01-20 14:10:07 10e20c0b43500cfb9bbc0eaa061c57514f715d87238f4d835880cd846b9ebd1f
----

Use the xref:../contrib/sqlite-schema.sql[sqlite-schema.sql] from the contrib
section to create a database, tables and the required fields:

[source,terminal]
----
$ cat contrib/sqlite-schema.sql | sqlite3 /var/lib/automx2/db.sqlite
----

.Click to see the SQLite schema definition
[%collapsible]
====
[source,sql]
----
include::../contrib/sqlite-schema.sql[]
----
====

Download the xref:../contrib/sqlite-generate.sh[sqlite-generate.sh] helper
script from the contrib section. Then change the script’s user-configurable
section to reflect your domain and server names and run the script to generate
the necessary SQL statements.

[source,bash]
----
include::../contrib/sqlite-generate.sh[lines=9..15]
----

The script will output the SQL statements to STDOUT. Verify your configuration
settings and use the script output to add entries to your sqlite database like
this:

[source,terminal]
----
$ contrib/sqlite-generate.sh | sqlite3 /var/lib/automx2/db.sqlite
----

This example assumes you have also set `/var/lib/automx2/db.sqlite` as path in
your `automx2.conf`.

[NOTE]
.Placeholders
====
In case you wonder about the macros in the configuration output: These are
link:https://wiki.mozilla.org/Thunderbird:Autoconfiguration:ConfigFileFormat#Placeholders[placeholders],
as documented by Mozilla.
====

Once you have populated the database automx2 is ready to run.


==== MySQL

To be done…


==== PostgreSQL

To be done…


==== Oracle

To be done…


==== Microsoft SQL Server

To be done…


[[runningautomx2]]
=== Running automx2

Running automx2 requires to start automx2 as service and serve its output
via a webserver to the public. You should not run automx2 with superuser
privileges. Use a dedicated user instead.

The following examples assume you have created a user `automx` and have
granted appropriate permissions to this user:

- Read permissions for the `automx2.conf` configuration file.
- Read and access permissions for the virtual Python environment.
- Read and access permissions for the SQLite database.

==== Systemd service

If your system uses systemd you may want to deploy the
following xref:../contrib/automx2.service[automx2.service] unit file from the
contrib section and place it in `/etc/systemd/system/automx2.service`:

[source,ini]
----
include::../contrib/automx2.service[]
----

Once you have installed the service you need to tell systemd to reload its
list of available services:

[source,terminal]
----
$ sudo systemctl daemon-reload
----

It should now be able to tell you about a service named automx2:

[source,terminal]
----
$ sudo systemctl status automx2
● automx2.service - "automx2 - mail account configuration service"
     Loaded: loaded (/etc/systemd/system/automx2.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
----

Next enable and start automx2 using the following command:

[source,terminal]
----
$ sudo systemctl enable automx2 --now
Created symlink /etc/systemd/system/multi-user.target.wants/automx2.service → /etc/systemd/system/automx2.service.
----

You should see automx2 enabled and running:

[source,terminal]
----
$ sudo systemctl status automx2
● automx2.service - "automx2 - mail account configuration service"
     Loaded: loaded (/etc/systemd/system/automx2.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-03-01 12:54:31 CET; 19s ago
   Main PID: 126966 (python)
      Tasks: 1 (limit: 4620)
     Memory: 46.1M
     CGroup: /system.slice/automx2.service
             └─126966 /srv/www/automx2/bin/python /srv/www/automx2/bin/flask run

Mar 01 12:54:32 mail python[126966]:    WARNING: This is a development server. Do not use it in a production deployment.
Mar 01 12:54:32 mail python[126966]:    Use a production WSGI server instead.
Mar 01 12:54:32 mail python[126966]:  * Debug mode: off
Mar 01 12:54:32 mail python[126966]: Running automx2 version 2021.1
Mar 01 12:54:32 mail python[126966]: Checking /home/automx/.automx2.conf
Mar 01 12:54:32 mail python[126966]: Checking /etc/automx2/automx2.conf
Mar 01 12:54:32 mail python[126966]: Checking /etc/automx2.conf
Mar 01 12:54:32 mail python[126966]: Reading /etc/automx2.conf
Mar 01 12:54:32 mail python[126966]: Config.get: loglevel = WARNING
Mar 01 12:54:32 mail python[126966]:  * Running on http://127.0.0.1:4243/ (Press CTRL+C to quit)
----

As systemd suggests there's a python service running on `127.0.0.1` on port `4243`:

[source, terminal]
----
$ sudo lsof -Pni tcp@localhost:4243
COMMAND    PID   USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
python  126966 automx    3u  IPv4 7758442      0t0  TCP 127.0.0.1:4243 (LISTEN)
----

You are ready to start testing automx2 locally as described in <<local-testing>>.


==== Command line

While logged in as an unprivileged user, change into the installation
directory and start the `contrib/flask.sh` script:

[source,terminal]
----
$ cd /srv/web/automx2
$ contrib/flask.sh run
----

This will start the flask service listening on IP address `127.0.0.1` and port
`4243`. These are the standard values for Flask and might collide with other
software you have installed. We therefore recommend that you use the parameters
`--host` and `--port` to override the defaults.

The typical launch command is this:

[source,terminal]
----
$ contrib/flask.sh run --host=127.0.0.1 --port=4243
----

[NOTE]
.Handling terminal output
====
The flask.sh script will deliberately keep automx2 running in the foreground,
and log data will be displayed in the terminal. If you press Ctrl-C or close the
shell session, the application will terminate. To run automx2 in the background,
you can use a window manager like link:https://www.gnu.org/software/screen/[GNU
Screen]
====

Now that automx2 is up and running, you need to configure the web server proxy
that will receive requests from the outside and forwards them to automx2.

[[local-testing]]
=== Testing automx2 on command line

Use `curl` to send a request to your local automx2-instance. The following
example assumes your service runs on localhost on port `4243`:

[source, terminal]
----
$ curl 'http://127.0.0.1:4243/mail/config-v1.1.xml?emailaddress=localpart@example.com'
<clientConfig version="1.1"><emailProvider id="automx2-100"><identity /><domain>example.com</domain><displayName>Example Inc.</displayName><displayShortName>Example</displayShortName><incomingServer type="imap"><hostname>mail.example.com</hostname><port>993</port><socketType>SSL</socketType><username>%EMAILADDRESS%</username><authentication>plain</authentication></incomingServer><incomingServer type="pop3"><hostname>mail.example.com</hostname><port>110</port><socketType>STARTTLS</socketType><username>%EMAILADDRESS%</username><authentication>plain</authentication></incomingServer><outgoingServer type="smtp"><hostname>mail.example.com</hostname><port>587</port><socketType>STARTTLS</socketType><username>%EMAILADDRESS%</username><authentication>plain</authentication></outgoingServer><incomingServer type="pop3"><hostname>mail.example.com</hostname><port>995</port><socketType>SSL</socketType><username>%EMAILADDRESS%</username><authentication>plain</authentication></incomingServer></emailProvider></clientConfig>
----

automx2 will output the configuration instructions as one-liner. Once you have
verified automx2 outputs configuration you are ready to setup and configure a
web server to serve automx data to the public.

=== Configuring a web server

While it is technically possible to run automx2 without a web server sitting in
front of it, we don't recommend doing that in a production environment. A web server
can provide features automx2 was designed not to have. Features such as transport
layer encryption aka `HTTPS` or, for example, the capability to rate-limit clients
are handled very well by full-fledged web servers working as reverse proxies. It
would be a waste to re-implement all this in a web service.

This section will explain how to configure a web server as a reverse proxy in
front of automx2. Before you set up the proxy you need to tell automx2 it
operates behind one. Add the `proxy_count` parameter to your automx2
configuration file or uncomment the parameter if it is already there:

[source,ini]
----
[automx2]
# A typical production setup would use loglevel = WARNING
loglevel = WARNING

# Echo SQL commands into log? Used for debugging.
db_echo = no

# SQLite database in a UNIX-like file system
db_uri = sqlite:////var/lib/automx2/db.sqlite    # <1>

# Number of proxy servers between automx2 and the client (default: 0).
# If your logs only show 127.0.0.1 or ::1 as the source IP for incoming
# connections, proxy_count probably needs to be changed.
proxy_count = 1    # <2>
----

<1> You might want to turn off echoing SQL commands to the log once you have
    verified automx2 works as expected.
<2> Set the number to reflect the number of proxies chained in front of automx2,
    i.e. the number of "proxy hops" a client's request must pass before it
    reaches automx2.


==== NGINX

The following example defines a `HTTP` server, which will listen on port
`80` for requests to either `autoconfig.example.com` or
`autodiscover.example.com`. All requests will be forwarded (proxied) to automx2,
which listens on `127.0.0.1` on port `4243` in this example. Requests to
`/initdb` are restricted to clients from `127.0.0.1` only. The
`proxy_set_header` directives will cause NGINX to pass relevant data about
incoming requests' origins.

[source,nginx]
----
include::../contrib/nginx-sample.conf[]
----


==== Apache

The following example defines a `HTTP` server, which will listen on port
`80` for requests to either `autoconfig.example.com` or
`autodiscover.example.com`. All requests will be forwarded (proxied) to
automx2, which listens on `127.0.0.1` on port `4243` in this example. Requests
to `/initdb` are restricted to clients from `127.0.0.1` only. The
`ProxyPreserveHost` directives will cause apache to pass relevant data about
incoming requests' origins.

[source,apache]
----
include::../contrib/apache-sample.conf[]
----


// vim: set ft=asciidoc:
